Repository esa/nanosat-mo-framework, pull requests merged in 2021-11, with the labels that each got.

#119 Avoid array declarations written in C-style syntax. Use java style.
  core/mo-services-impl/nmf-platform-generic-impl/src/main/java/esa/mo/platform/impl/util/HelperGPS.java
  core/nmf-composites/nanosat-mo-supervisor/src/main/java/esa/mo/nmf/nanosatmosupervisor/NanosatMOSupervisorBasicImpl.java
  core/nmf-package-lib/src/main/java/esa/mo/nmf/nmfpackage/NMFPackageCreator.java
  core/nmf-package-lib/src/main/java/esa/mo/nmf/nmfpackage/tests/SimpleDemoPackageCreation.java
  core/nmf-package-lib/src/main/java/esa/mo/nmf/nmfpackage/tests/SimpleDemoPackageInstallation.java
  mission/simulator/opssat-gps-simulator/src/main/java/opssat/simulator/TestClass.java
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/main/ESASimulator.java
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/tcp/TCPServerReceiveOnly.java
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/util/CommandDescriptor.java
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/util/SimulatorSpacecraftState.java
  mission/simulator/platform-services-impl/src/main/java/esa/mo/platform/impl/provider/softsim/AutonomousADCSSoftSimAdapter.java
  sdk/examples/ground/camera-acquisitor-system-ground/src/main/java/esa/mo/ground/cameraacquisotorground/SpringInitiator.java
  sdk/examples/ground/directory-consumer/src/main/java/esa/mo/ground/echo/AlertTest2.java
  sdk/examples/ground/directory-consumer/src/main/java/esa/mo/ground/echo/DemoGroundDirectory.java
  sdk/examples/ground/echo/src/main/java/esa/mo/ground/echo/AlertTest2.java
  sdk/examples/ground/echo/src/main/java/esa/mo/ground/echo/EchoGround.java
  sdk/examples/ground/facebook/src/main/java/esa/mo/nmf/ground/facebook/Push2Facebook.java
  sdk/examples/ground/set-and-command/src/main/java/esa/mo/ground/setandcommand/DemoSetAndCommand.java
  sdk/examples/ground/simple-ground/src/main/java/esa/mo/ground/simpleground/SimpleGround.java
  sdk/examples/space/adcs-eds/src/main/java/esa/mo/nmf/apps/ADCSApp.java
  sdk/examples/space/all-mc-services-with-sim/src/main/java/esa/mo/nmf/apps/MonolithicProviderDemo.java
  sdk/examples/space/all-mc-services/src/main/java/esa/mo/nmf/apps/AllInOne.java
  sdk/examples/space/benchmark/src/main/java/esa/mo/nmf/apps/BenchmarkApp.java
  sdk/examples/space/blank/src/main/java/esa/mo/nmf/apps/BlankApp.java
  sdk/examples/space/camera-acquisitor-system/src/main/java/esa/mo/nmf/apps/CameraAcquisitorSystemApp.java
  sdk/examples/space/camera/src/main/java/esa/mo/nmf/apps/SnapNMF.java
  sdk/examples/space/echo/src/main/java/esa/mo/nmf/apps/EchoSpace.java
  sdk/examples/space/gps/src/main/java/esa/mo/nmf/apps/DemoGPSData.java
  sdk/examples/space/hello-world-full/src/main/java/esa/mo/nmf/apps/DemoHelloWorldFull.java
  sdk/examples/space/hello-world-simple/src/main/java/esa/mo/nmf/apps/DemoHelloWorldSimple.java
  sdk/examples/space/multistage-action/src/main/java/esa/mo/nmf/apps/FiveStagesAction.java
  sdk/examples/space/payloads-test/src/main/java/esa/mo/nmf/apps/PayloadsTestApp.java
  sdk/examples/space/periodic-alert/src/main/java/esa/mo/nmf/apps/Demo10secAlert.java
  sdk/examples/space/picture-processor/src/main/java/esa/mo/nmf/apps/pictureprocessor/PictureProcessorApp.java
  sdk/examples/space/publish-clock/src/main/java/esa/mo/nmf/apps/PushClock.java
  sdk/examples/space/serialized-object/src/main/java/esa/mo/nmf/apps/DemoSerialObject.java
  sdk/examples/space/waveform/src/main/java/esa/mo/nmf/apps/Waveform.java
  sdk/tools/consumer-test-tool/src/main/java/esa/mo/nmf/ctt/guis/ConsumerTestToolGUI.java
Labels: refactor

#128 Bug #1158 Wrong GPS TIMEA log format in simulator
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java
  mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java
Labels: bug

#131 Issue #1169 [examples] On-board communications
  core/helper-tools/src/main/java/esa/mo/helpertools/misc/Const.java
  core/nmf-composites/nmf-mo-adapters/space-mo-adapter/src/main/java/esa/mo/nmf/spacemoadapter/SpaceMOApdapterImpl.java
  docs/source/apps/main.rst
  sdk/examples/space/pom.xml
  sdk/examples/space/space-to-space-supervisor/pom.xml
  sdk/examples/space/space-to-space-supervisor/src/main/java/esa/mo/nmf/apps/DemoSpace2Supervisor.java
  sdk/examples/space/space-to-space-supervisor/src/main/java/esa/mo/nmf/apps/Space2SupervisorAdapter.java
  sdk/examples/space/space-to-space/pom.xml
  sdk/examples/space/space-to-space/src/main/java/esa/mo/nmf/apps/DemoSpace2Space.java
  sdk/examples/space/space-to-space/src/main/java/esa/mo/nmf/apps/Space2SpaceAdapter.java
Labels: feature, documentation

#129 Bug #1157 Wrong GPS time in simulator GNSS logs
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/threading/SimulatorNode.java
  mission/simulator/opssat-spacecraft-simulator/src/main/java/opssat/simulator/util/SimulatorData.java
  mission/simulator/platform-services-impl/src/test/java/esa/nmf/test/GPSSoftSimAdapterTest.java
Labels: bug
